Fix deprecations
swoole/ide-helper pull request #35
Opened 2022-02-16 04:23 UTC by dmitryuk

I think it's a time to remove deprecations to the methods. The package only IDE-helper and will not affect to some projects.
```
  1x: Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "Iterator::key()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "Iterator::rewind()" might add "void" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "Iterator::next()" might add "void" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Swoole\ArrayObject" now to avoid errors or add an explicit @return annotation to suppress this message.

```

2022-02-16 04:56 UTC, sy-records requested changes
Thank you for the PR.
But it should be submitted to [swoole/library](https://github.com/swoole/library).

2022-02-16 06:16 UTC, dmitryuk commented
No way to do it in `swoole/library`, because `mixed` and `union` types doesn't support for php < 8.0. I can drop support of `php:^7.0` in `swoole/library`, but I don't think it needed right now. 
IDE-helper library doesn't affect to current code.

2022-02-16 06:45 UTC, sy-records commented
But this part of the code is automatically synced over.
cc @deminy

2022-02-18 05:04 UTC, dmitryuk commented
@sy-records Can't see repo branch v5 on swoole-src and swoole-library. Can you create it?

2022-02-18 05:07 UTC, sy-records commented
hi, @dmitryuk
master = v5

2022-02-22 05:28 UTC, closed without merging